In [1]:
import sys 
sys.path.append("C:/Users/L2S/Desktop/Efficient_and_reliable_GP/Code/")
from dataset_generation import sampler, extract_K_samples

# Parameters

In [2]:
# Dataset
space_size              = 1
N_function              = 500
all_function_parameters = {"Power sinus 1D"                : {"Power" : 1},
                           "Heaviside 1D"                  : {"x gaps" : [0, 0.5, 1], "steps value" : [1, -1], "sigma noises" : [0.2, 0.2]},
                           "Multimodal sinus 1D"           : {"x gaps" : [0, 0.5, 1], "speeds value" : [1, 2]},
                           "Noisy sinus 1D"                : {"sigma noise" : 0.2},
                           "Sinus times x 1D"              : {},
                           "Sinus cardinal 1D"             : {},
                           "Slide function"                : {},
                           "Two bumps"                     : {},
                           "Power sinus 2D"                : {"Power" : 1},
                           "Heaviside 2D"                  : {"x gaps" : [0, 1, 2], "steps value" : [1, -1], "sigma noises" : [0.2, 0.2]},
                           "Multimodal sinus 2D"           : {"x gaps" : [0, 1, 2], "speeds value" : [1, 2]},
                           "Noisy sinus 2D"                : {"sigma noise" : 0.2},
                           "Sinus times x 2D"              : {},
                           "Sinus cardinal 2D"             : {},
                           "Gaussian process trajectory"   : {"sigma0" : 1, "theta" : 1},
                           "Concrete compressive strength" : {},
                           "Energy efficiency"             : {},
                           "Auto mpg"                      : {},
                           "Combined cycle power plant"    : {},
                           "Airfoil self-noise"            : {},
                           "Morokoff & caflisch 1"         : {"Dimension" : 2},
                           "Morokoff & caflisch 2"         : {"Dimension" : 2},
                           "Branin"                        : {},
                           "Branin hoo"                    : {},
                           "Goldstein"                     : {},
                           "Goldstein price"               : {},
                           "Rosenbrock4"                   : {},
                           "Hartman4"                      : {},
                           "Hartman6"                      : {},
                           "Sphere6"                       : {},
                           "Iooss1"                        : {},
                           "Iooss2"                        : {},
                           "Wing weight"                   : {},
                           "Sobol"                         : {"a" : [1, 10]},
                           "Two input toy"                 : {},
                           "Highly non linear"             : {},
                           "Mystery"                       : {},
                           "Six hump camelback"            : {},
                           "Ishigami"                      : {}
                          }
N_train                 = 25
N_test                  = 25

# 1 - 1D synthetic datasets

### 1.1 - Power sinus 1D

In [3]:
function_name = "Power sinus 1D"

In [4]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.51375864]
 [0.47293386]
 [0.12280186]
 [0.24576777]
 [0.43258818]]
[-0.08634043  0.16924303  0.69727358  0.99964646  0.41100934]


### 1.2 - Heaviside 1D

In [5]:
function_name       = "Heaviside 1D"

In [6]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.37890159]
 [0.68083697]
 [0.67590193]
 [0.99165844]
 [0.96011552]]
[ 1.12132343 -0.51949248 -1.00218091 -0.78644317 -0.61387015]


### 1.3 - Multimodal sinus 1D

In [7]:
function_name = "Multimodal sinus 1D"

In [8]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.30340693]
 [0.18896167]
 [0.54172646]
 [0.55564934]
 [0.58643712]]
[0.94422419 0.92735505 0.5006506  0.64369002 0.88486349]


### 1.4 - Noisy sinus 1D

In [9]:
function_name = "Noisy sinus 1D"

In [10]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.05021509]
 [0.37260425]
 [0.19561651]
 [0.3138971 ]
 [0.64992918]]
[-0.02087627  0.39187482  1.19936719  1.172127   -0.63207529]


### 1.5 - Sinus times x 1D

In [11]:
function_name = "Sinus times x 1D"

In [12]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.81757725]
 [0.28967981]
 [0.88922058]
 [0.31944529]
 [0.78938843]]
[-0.7449792   0.28072335 -0.5701591   0.28951504 -0.76533705]


### 1.6 - Sinus cardinal 1D

In [13]:
function_name = "Sinus cardinal 1D"

In [14]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.26283671]
 [0.83060555]
 [0.14759143]
 [0.62487132]
 [0.47574676]]
[ 3.79227505 -1.05280703  5.4205685  -1.13068854  0.31907415]


### 1.7 - Slide function

In [15]:
function_name = "Slide function"

In [16]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.2303347 ]
 [0.04403535]
 [0.07658567]
 [0.35284584]
 [0.93854066]]
[-0.17730057 -0.03508565 -0.06077574 -0.2615433  -0.48487881]


### 1.8 - Two bumps

In [17]:
function_name = "Two bumps"

In [18]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.68635977]
 [0.6214025 ]
 [0.2555427 ]
 [0.56087884]
 [0.08943365]]
[ 0.42560346  0.39421668 -0.99456474  0.28515509 -1.13295071]


# 2 - 2D Synthetic datasets

### 2.1 - Power sinus 2D

In [19]:
function_name = "Power sinus 2D"

In [20]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[1.32391482e-05 8.47722961e-01]
 [6.47741548e-02 1.23361767e-02]
 [6.85722788e-01 4.30933159e-02]
 [6.31505630e-01 1.78889802e-01]
 [2.90423794e-01 8.70724107e-01]]
[-0.81729546  0.46576464 -0.99115495 -0.92885899  0.84817057]


### 2.2 - Heaviside 2D

In [21]:
function_name       = "Heaviside 2D"

In [22]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.11754584 0.87851169]
 [0.99307395 0.84576479]
 [0.78490957 0.65839991]
 [0.60546216 0.85944886]
 [0.30627771 0.55560238]]
[ 1.16116247 -1.2519708  -0.86677756 -0.84187941  0.7617337 ]


### 2.3 - Multimodal sinus 2D

In [23]:
function_name = "Multimodal sinus 2D"

In [24]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.54357295 0.06580707]
 [0.55606742 0.06985283]
 [0.50548581 0.25773201]
 [0.09995588 0.63439088]
 [0.06357198 0.26560677]]
[-0.6344177  -0.71118349 -0.99655333 -0.99516732  0.87878089]


### 2.4 - Noisy sinus 2D

In [25]:
function_name = "Noisy sinus 2D"

In [26]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.02462396 0.29455496]
 [0.89171626 0.10253349]
 [0.63976426 0.8163482 ]
 [0.28908152 0.55499067]
 [0.6464218  0.40983512]]
[ 0.75548162  0.17937636  0.38591224 -0.98287651  0.4719261 ]


### 2.5 - Sinus times x 2D

In [27]:
function_name = "Sinus times x 2D"

In [28]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.15081212 0.06749803]
 [0.78228629 0.29131952]
 [0.05724256 0.7143168 ]
 [0.72604995 0.92651159]
 [0.06713282 0.61100781]]
[ 0.21399686  0.47900858 -0.7644912  -1.3524101  -0.61018492]


### 2.6 - Sinus cardinal 2D

In [29]:
function_name = "Sinus cardinal 2D"

In [30]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.00807021 0.46813102]
 [0.56974841 0.58348619]
 [0.5676771  0.06738048]
 [0.5149864  0.14030435]
 [0.84678332 0.86964352]]
[ 0.3128414   0.71173291 -1.18154682 -1.26372305 -0.56969116]


# 3 - Gaussian process trajectory

In [31]:
function_name = "Gaussian process trajectory"

In [32]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.36110456]
 [0.6209443 ]
 [0.86156845]
 [0.21010388]
 [0.3543349 ]]
[-1.63997055 -1.77064662 -1.83441552 -1.57977363 -1.6368092 ]


# 4 - UCI machine learning datasets

### 4.1 - Concrete compressive strength - $N=1030$ and $d=8$

In [33]:
function_name = "Concrete compressive strength"

In [34]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[ 362.6  189.     0.   164.9   11.6  944.7  755.8    7. ]
 [ 349.     0.     0.   192.     0.  1056.   809.    90. ]
 [ 310.     0.     0.   192.     0.   970.   850.     7. ]
 [ 323.7  282.8    0.   183.8   10.3  942.7  659.9    7. ]
 [ 157.   214.   152.   200.     9.   819.   704.    28. ]]
[55.9  40.66 14.99 49.8  33.05]


### 4.2 - Energy efficiency - $N=768$ and $d=8$

In [35]:
function_name = "Energy efficiency"

In [36]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[6.2000e-01 8.0850e+02 3.6750e+02 2.2050e+02 3.5000e+00 5.0000e+00
  4.0000e-01 2.0000e+00]
 [7.6000e-01 6.6150e+02 4.1650e+02 1.2250e+02 7.0000e+00 2.0000e+00
  1.0000e-01 5.0000e+00]
 [7.9000e-01 6.3700e+02 3.4300e+02 1.4700e+02 7.0000e+00 4.0000e+00
  2.5000e-01 3.0000e+00]
 [9.8000e-01 5.1450e+02 2.9400e+02 1.1025e+02 7.0000e+00 3.0000e+00
  0.0000e+00 0.0000e+00]
 [7.9000e-01 6.3700e+02 3.4300e+02 1.4700e+02 7.0000e+00 3.0000e+00
  0.0000e+00 0.0000e+00]]
[17.15 32.31 39.81 15.55 29.9 ]


### 4.3 - Auto mpg - $N=398$ and $d=7$

In [37]:
function_name = "Auto mpg"

In [38]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[1.210e+02 4.000e+00 1.120e+02 2.933e+03 1.450e+01 7.200e+01 2.000e+00]
 [2.320e+02 6.000e+00 1.000e+02 2.901e+03 1.600e+01 7.400e+01 1.000e+00]
 [4.000e+02 8.000e+00 1.800e+02 4.220e+03 1.110e+01 7.700e+01 1.000e+00]
 [2.500e+02 6.000e+00 7.200e+01 3.432e+03 2.100e+01 7.500e+01 1.000e+00]
 [1.190e+02 4.000e+00 9.200e+01 2.434e+03 1.500e+01 8.000e+01 3.000e+00]]
[18. 19. 16. 15. 37.]


### 4.4 - Combined cycle power plant - $N=9568$ and $d=4$

In [39]:
function_name = "Combined cycle power plant"

In [40]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[  30.36   74.87 1008.96   61.87]
 [   9.1    39.42 1025.28   68.78]
 [  30.35   69.51 1009.95   39.24]
 [  30.39   71.8  1010.87   64.11]
 [  29.56   52.84 1006.09   42.17]]
[435.31 471.85 430.07 435.82 436.46]


### 4.5 - Airfoil self-noise - $N=1503$ and $d=4$

In [41]:
function_name = "Airfoil self-noise"

In [42]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[3.15000e+03 7.20000e+00 1.52400e-01 3.96000e+01 9.09175e-03]
 [1.25000e+03 1.74000e+01 2.54000e-02 3.17000e+01 1.76631e-02]
 [6.30000e+03 0.00000e+00 2.54000e-02 5.55000e+01 4.12290e-04]
 [3.15000e+03 1.26000e+01 1.52400e-01 3.96000e+01 5.84113e-02]
 [2.00000e+02 1.54000e+01 5.08000e-02 7.13000e+01 2.64269e-02]]
[111.818 128.306 136.103 106.26  123.595]


# 5 - Literature datasets 2D

### 5.1 - Branin

In [43]:
function_name = "Branin"

In [44]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.41993135 0.05377657]
 [0.2047982  0.37209348]
 [0.70877178 0.17730857]
 [0.34342434 0.99816565]
 [0.80913441 0.12474647]]
[ 23.76009607  22.3823011   19.96193643 104.32434487  16.73184217]


### 5.2 - Branin hoo

In [45]:
function_name = "Branin hoo"

In [46]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.97979207 0.53706733]
 [0.58413805 0.87431733]
 [0.4667514  0.23228635]
 [0.25388893 0.89811489]
 [0.97359678 0.76029808]]
[-0.49129388  1.43366253 -0.93924683 -0.23457078  0.43749689]


### 5.3 - Goldstein

In [47]:
function_name = "Goldstein"

In [48]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.35467055 0.14608732]
 [0.85317987 0.57389952]
 [0.32178793 0.17142789]
 [0.91209749 0.24238687]
 [0.49300198 0.09670938]]
[  194.66124161   683.65562267   595.40786012 49415.53919879
  5638.70883185]


### 5.4 - Goldstein price

In [49]:
function_name = "Goldstein price"

In [50]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.21447983 0.34433852]
 [0.72946075 0.65644867]
 [0.91801624 0.02465542]
 [0.01965176 0.65843886]
 [0.26541785 0.44137394]]
[-0.69615938 -0.77365235  1.2988352   0.67901355 -1.4237286 ]


### 5.5 - Iooss1

In [51]:
function_name = "Iooss1"

In [52]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.42682712 0.54503973]
 [0.08923897 0.46497497]
 [0.08850342 0.09488035]
 [0.92837228 0.03673159]
 [0.69160578 0.93428619]]
[2.82107468 1.81696791 0.84855952 1.8409372  0.29753806]


### 5.6 - Iooss2

In [53]:
function_name = "Iooss2"

In [54]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.98206894 0.33332952]
 [0.28612555 0.76107057]
 [0.75821182 0.55768428]
 [0.52534799 0.67674776]
 [0.80752324 0.55904406]]
[1.52681848 0.23650204 1.2022355  0.75287232 1.28822773]


### 5.7 - Two input toy

In [55]:
function_name = "Two input toy"

In [56]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.98045036 0.8519382 ]
 [0.58162081 0.22195994]
 [0.89829517 0.35879964]
 [0.29501316 0.02951243]
 [0.67558436 0.70181525]]
[ 4.5263488  10.05324464  7.73494917 13.40366163  5.51559798]


### 5.8 - Highly non linear

In [57]:
function_name = "Highly non linear"

In [58]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.67718139 0.02836157]
 [0.67538321 0.7362458 ]
 [0.99571753 0.53836366]
 [0.69159829 0.06229173]
 [0.45695218 0.95902744]]
[7.92251522 8.28825331 7.80686312 7.8418645  8.82876987]


### 5.9 - Mystery

In [59]:
function_name = "Mystery"

In [60]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.87996008 0.53085321]
 [0.98654588 0.81282046]
 [0.0959822  0.48863473]
 [0.47136992 0.13783046]
 [0.22772942 0.28578107]]
[7.39504313 6.59686371 7.48578889 9.53836375 8.68613089]


### 5.10 - Six hump camelback

In [61]:
function_name = "Six hump camelback"

In [62]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.40274758 0.44547048]
 [0.58127235 0.62819312]
 [0.76306452 0.79726856]
 [0.95644575 0.73263794]
 [0.61244743 0.19665962]]
[ 0.55379397  0.23736784  2.01837559  2.51686935 -0.47719667]


# 6 - Literature datasets nD

### 6.1 - Morokoff & Caflisch 1

In [63]:
function_name = "Morokoff & caflisch 1"

In [64]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.94751156 0.06919817]
 [0.80814293 0.08238707]
 [0.52877951 0.89803209]
 [0.48562144 0.39028123]
 [0.96236715 0.17646844]]
[0.57613211 0.58057208 1.55047852 0.97953572 0.92722777]


### 6.2 - Morokoff & Caflisch 2

In [65]:
function_name = "Morokoff & caflisch 2"

In [66]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.08414485 0.53169134]
 [0.91122498 0.02039367]
 [0.77157248 0.25769586]
 [0.28802401 0.21039333]
 [0.27552222 0.30422153]]
[1.25025187 0.95793152 0.95124193 1.36167274 1.29970324]


### 6.3 - Rosenbrock4

In [67]:
function_name = "Rosenbrock4"

In [68]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.12590416 0.9463079  0.91629863 0.70015092]
 [0.83547337 0.2433305  0.96886138 0.35789151]
 [0.50609529 0.75160439 0.46230512 0.21094911]
 [0.42415028 0.99518226 0.62805579 0.59767319]
 [0.78622992 0.2057872  0.00301286 0.36379694]]
[ 1.85236531  2.07695876 -0.63766192  1.42315093 -0.22939095]


### 6.4 - Hartman4

In [69]:
function_name = "Hartman4"

In [70]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.82480399 0.33111009 0.03700553 0.65263459]
 [0.19991496 0.99305179 0.50372272 0.98909036]
 [0.86269296 0.25426469 0.78921365 0.77432906]
 [0.70251673 0.80607023 0.65875119 0.29042923]
 [0.53702703 0.01531005 0.44912194 0.03971423]]
[ 1.04624238  0.99468865  0.19623568  0.417619   -0.24827123]


### 6.5 - Hartman6

In [71]:
function_name = "Hartman6"

In [72]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.40238815 0.90446767 0.19790116 0.26562169 0.32980303 0.07694418]
 [0.35224393 0.33527526 0.33045671 0.79225915 0.00239764 0.19457393]
 [0.54458691 0.79765161 0.17886159 0.17787308 0.90737924 0.5387214 ]
 [0.11270803 0.80799955 0.73259237 0.95870018 0.9719421  0.73700996]
 [0.95175124 0.68253498 0.1171161  0.33642104 0.32319328 0.10904534]]
[-1.94498054 -1.39706593 -1.33887471 -1.33323036 -1.3426609 ]


### 6.6 - Sphere6

In [73]:
function_name = "Sphere6"

In [74]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.60429529 0.28942435 0.12369415 0.52427264 0.83278493 0.62813293]
 [0.93419551 0.82906276 0.62956288 0.93809934 0.18693447 0.88426985]
 [0.13499271 0.21246913 0.17625248 0.89852536 0.27516924 0.25836393]
 [0.43843822 0.08629528 0.7876462  0.37245069 0.06171488 0.42141673]
 [0.43777155 0.24577656 0.01744882 0.96485177 0.27965724 0.08608984]]
[-1.88205801 -1.85994655 -1.91871167 -1.91981689 -1.92046789]


### 6.7 - Wing weight

In [75]:
function_name = "Wing weight"

In [76]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[ 1.57726946e+02  2.99071426e+02  6.38047787e+00  5.24758723e+00
   2.84054124e+01  8.16287994e-01  1.43278621e-01  3.09292483e+00
   2.07026539e+03  3.78399625e-02]
 [ 1.75117047e+02  2.70207456e+02  8.02384214e+00 -1.17415520e+00
   3.47892648e+01  8.21503787e-01  1.76982121e-01  5.63912509e+00
   2.13285484e+03  3.82866755e-02]
 [ 1.68811867e+02  2.35482091e+02  9.04947090e+00 -4.68288006e+00
   2.65706776e+01  7.71573441e-01  1.66547184e-01  4.32985106e+00
   1.84247094e+03  5.76567874e-02]
 [ 1.55445975e+02  2.90157763e+02  9.35210462e+00 -4.81358529e+00
   2.28338675e+01  7.18707915e-01  8.69428599e-02  2.73158418e+00
   2.46807463e+03  4.68959168e-02]
 [ 1.99758323e+02  2.31038050e+02  9.79183032e+00 -1.96259103e+00
   1.74705443e+01  6.13727484e-01  1.67764629e-01  4.24315885e+00
   1.81744355e+03  7.46300767e-02]]
[ 322.5923142   652.90904204           nan 2009.20570969           nan]


C:\Users/L2S/Desktop/Efficient_and_reliable_GP/Code\dataset_generation.py:363: RuntimeWarning: invalid value encountered in scalar power
  y                                       = 0.036 * x1**0.758 * x2**0.0035 * (x3 / np.cos(x4)**2)**0.6 * x5**0.006 * x6**0.04 * (100 * x7 / np.cos(x4))**(-0.3) * (x8 * x9)**0.49 + x1 * x10


### 6.8 - Sobol

In [77]:
function_name = "Sobol"

In [78]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.08152359 0.08060389]
 [0.13313787 0.4132952 ]
 [0.68696507 0.50001548]
 [0.97369639 0.86802264]
 [0.26719025 0.05017312]]
[1.41930723 1.16046563 0.79448687 1.50951101 1.03578558]


### 6.9 - Ishigami

In [79]:
function_name = "Ishigami"

In [80]:
X_function, Y_function = sampler          (space_size, N_function, function_name, all_function_parameters)
X, Y                   = extract_K_samples(X_function, Y_function, N_train + N_test)
X_observed, Y_observed = X[:N_train], Y[:N_train]
X_test    , Y_test     = X[N_train:], Y[N_train:]
print(X_observed[:5])
print(Y_observed[:5])

[[0.87357033 0.71552332 0.21732282]
 [0.4902317  0.21170384 0.2831974 ]
 [0.71199024 0.50857101 0.47979943]
 [0.62451316 0.12603279 0.60595974]
 [0.10854349 0.43699486 0.47114745]]
[8.10001621 6.5200116  0.99192404 4.26421333 0.410472  ]
