In [1]:
import sys 
sys.path.append("C:/Users/L2S/Desktop/Efficient_and_reliable_GP/")

from Code.data_generation.samplers           import sampler, extract_K_samples
from Code.Parameters     .sampler_parameters import sampler_parameters

# Parameters

In [2]:
# Sampler
N_function = 500
N_train    = 25
N_test     = 25

# 1 - 1D synthetic datasets

### 1.1 - Power sinus 1D

In [3]:
function_name = "Power sinus 1D"

In [4]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.55485824]
 [0.15829831]
 [0.45073976]
 [0.04459603]
 [0.02438132]]
[-0.33789974  0.83855068  0.3045931   0.2765528   0.15259389]


### 1.2 - Heaviside 1D

In [5]:
function_name       = "Heaviside 1D"

In [6]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.93830446]
 [0.24068152]
 [0.96091664]
 [0.22405765]
 [0.17642717]]
[-1.08619352  1.12463533 -0.71739169  1.06255131  0.9377286 ]


### 1.3 - Multimodal sinus 1D

In [7]:
function_name = "Multimodal sinus 1D"

In [8]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.51117825]
 [0.13035271]
 [0.34180397]
 [0.7357491 ]
 [0.27413679]]
[0.1400085  0.7304839  0.83820039 0.17812637 0.98852226]


### 1.4 - Noisy sinus 1D

In [9]:
function_name = "Noisy sinus 1D"

In [10]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.98880766]
 [0.84035979]
 [0.1938735 ]
 [0.64260131]
 [0.5599143 ]]
[ 0.21851645 -0.88330548  0.94287073 -1.1127132  -0.40670658]


### 1.5 - Sinus times x 1D

In [11]:
function_name = "Sinus times x 1D"

In [12]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.04407883]
 [0.81295718]
 [0.70881715]
 [0.19032571]
 [0.07783341]]
[ 0.0120524  -0.75017773 -0.68521932  0.17710338  0.03656459]


### 1.6 - Sinus cardinal 1D

In [13]:
function_name = "Sinus cardinal 1D"

In [14]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.233312  ]
 [0.67788885]
 [0.92705416]
 [0.63854358]
 [0.77816551]]
[ 4.26256639 -1.32632327 -0.47726775 -1.19748762 -1.2650031 ]


### 1.7 - Slide function

In [15]:
function_name = "Slide function"

In [16]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.99546174]
 [0.87983682]
 [0.97602487]
 [0.31691319]
 [0.0206449 ]]
[-0.48728348 -0.47859867 -0.48687007 -0.23781904 -0.01648782]


### 1.8 - Two bumps

In [17]:
function_name = "Two bumps"

In [18]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.29207424]
 [0.76143453]
 [0.37134045]
 [0.30820095]
 [0.76546699]]
[1.08765435 0.17629547 0.51664021 0.99890974 0.20191216]


# 2 - 2D Synthetic datasets

### 2.1 - Power sinus 2D

In [19]:
function_name = "Power sinus 2D"

In [20]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.36605183 0.68401477]
 [0.012821   0.73899464]
 [0.52291991 0.49694529]
 [0.0671443  0.3723069 ]
 [0.89542209 0.75486372]]
[ 0.30941496 -0.99993493  0.1244929   0.3713284  -0.81007122]


### 2.2 - Heaviside 2D

In [21]:
function_name       = "Heaviside 2D"

In [22]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.4808141  0.0608431 ]
 [0.62657816 0.64717669]
 [0.39655666 0.44245113]
 [0.92593395 0.14732305]
 [0.28206318 0.06555738]]
[ 1.114277   -0.97815326  0.9123415  -1.18207091  1.07494898]


### 2.3 - Multimodal sinus 2D

In [23]:
function_name = "Multimodal sinus 2D"

In [24]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.62807218 0.71890634]
 [0.92130478 0.23511918]
 [0.55464992 0.93356212]
 [0.5136303  0.46308121]
 [0.6317932  0.37734263]]
[ 0.82002935  0.83207637  0.07399823 -0.14580427  0.05737055]


### 2.4 - Noisy sinus 2D

In [25]:
function_name = "Noisy sinus 2D"

In [26]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.02197518 0.62050777]
 [0.52107156 0.44960096]
 [0.67740844 0.43244349]
 [0.53864424 0.99518565]
 [0.43413077 0.25745885]]
[-1.10316931 -0.29112505  0.73575341 -0.01840208 -1.13593329]


### 2.5 - Sinus times x 2D

In [27]:
function_name = "Sinus times x 2D"

In [28]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.40273614 0.46176701]
 [0.13016276 0.05159526]
 [0.84520986 0.45242625]
 [0.47732752 0.70288857]
 [0.99259857 0.68229524]]
[-0.65025499  0.16530436  1.23994478  1.06857274 -1.49183359]


### 2.6 - Sinus cardinal 2D

In [29]:
function_name = "Sinus cardinal 2D"

In [30]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.49415186 0.50353314]
 [0.26224381 0.83861757]
 [0.2761217  0.37947652]
 [0.28465163 0.7212516 ]
 [0.88890419 0.26154255]]
[-0.01457881  0.5379017  -1.2647799   0.03686498  0.70465122]


# 3 - Gaussian process trajectory

In [31]:
function_name = "Gaussian process trajectory"

In [32]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.60865154]
 [0.50982679]
 [0.78574573]
 [0.70728209]
 [0.08968428]]
[-1.77081123 -1.72089056 -1.83289727 -1.81181915 -1.55312595]


# 4 - UCI machine learning datasets

### 4.1 - Concrete compressive strength - $N=1030$ and $d=8$

In [33]:
function_name = "Concrete compressive strength"

In [34]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[ 349.     0.     0.   192.     0.  1047.   806.     7. ]
 [ 141.3  212.     0.   203.5    0.   971.8  748.5   90. ]
 [ 150.9    0.   183.9  166.6   11.6  991.2  772.2   28. ]
 [ 305.3  203.5    0.   203.5    0.   965.4  631.     3. ]
 [ 475.     0.    59.   142.     1.9 1098.   641.    28. ]]
[18.13 39.66 15.57 14.14 57.23]


### 4.2 - Energy efficiency - $N=768$ and $d=8$

In [35]:
function_name = "Energy efficiency"

In [36]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[6.6000e-01 7.5950e+02 3.1850e+02 2.2050e+02 3.5000e+00 2.0000e+00
  2.5000e-01 1.0000e+00]
 [8.6000e-01 5.8800e+02 2.9400e+02 1.4700e+02 7.0000e+00 3.0000e+00
  1.0000e-01 1.0000e+00]
 [8.6000e-01 5.8800e+02 2.9400e+02 1.4700e+02 7.0000e+00 3.0000e+00
  4.0000e-01 4.0000e+00]
 [9.8000e-01 5.1450e+02 2.9400e+02 1.1025e+02 7.0000e+00 4.0000e+00
  1.0000e-01 4.0000e+00]
 [8.6000e-01 5.8800e+02 2.9400e+02 1.4700e+02 7.0000e+00 4.0000e+00
  2.5000e-01 5.0000e+00]]
[13.17 26.91 31.66 24.04 28.31]


### 4.3 - Auto mpg - $N=398$ and $d=7$

In [37]:
function_name = "Auto mpg"

In [38]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[3.180e+02 8.000e+00 1.500e+02 3.940e+03 1.320e+01 7.600e+01 1.000e+00]
 [3.050e+02 8.000e+00 1.450e+02 3.425e+03 1.320e+01 7.800e+01 1.000e+00]
 [1.080e+02 4.000e+00 9.300e+01 2.391e+03 1.550e+01 7.400e+01 3.000e+00]
 [1.080e+02 4.000e+00 7.500e+01 2.350e+03 1.680e+01 8.100e+01 3.000e+00]
 [1.990e+02 6.000e+00 9.700e+01 2.774e+03 1.550e+01 7.000e+01 1.000e+00]]
[13.  19.2 26.  32.4 18. ]


### 4.4 - Combined cycle power plant - $N=9568$ and $d=4$

In [39]:
function_name = "Combined cycle power plant"

In [40]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[  11.93   41.38 1021.76   57.63]
 [  11.44   34.03 1018.57   74.06]
 [   5.76   40.07 1013.22   62.99]
 [  13.65   44.6  1017.99   87.04]
 [  21.83   62.91 1011.07   91.34]]
[473.88 476.06 494.67 466.06 443.76]


### 4.5 - Airfoil self-noise - $N=1503$ and $d=4$

In [41]:
function_name = "Airfoil self-noise"

In [42]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[5.00000e+03 8.90000e+00 1.01600e-01 3.96000e+01 1.24596e-02]
 [6.30000e+02 2.22000e+01 2.54000e-02 3.96000e+01 2.29028e-02]
 [3.15000e+02 0.00000e+00 3.04800e-01 3.17000e+01 3.31266e-03]
 [2.00000e+03 5.40000e+00 1.52400e-01 3.96000e+01 4.85029e-03]
 [2.00000e+03 9.90000e+00 1.52400e-01 5.55000e+01 2.08438e-02]]
[113.08  137.026 122.765 124.647 119.505]


# 5 - Literature datasets 2D

### 5.1 - Branin

In [43]:
function_name = "Branin"

In [44]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.87199828 0.14866696]
 [0.06062317 0.65538147]
 [0.50037372 0.36845341]
 [0.82582978 0.69183927]
 [0.8409415  0.44585414]]
[ 8.27841959 27.84695461  9.5845178  96.85461173 40.54748024]


### 5.2 - Branin hoo

In [45]:
function_name = "Branin hoo"

In [46]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.05257513 0.19516718]
 [0.48946159 0.49115926]
 [0.63929669 0.50164285]
 [0.02619709 0.33895791]
 [0.71547454 0.62579211]]
[ 1.85125893 -0.62105532 -0.16709008  1.44288808  0.60989574]


### 5.3 - Goldstein

In [47]:
function_name = "Goldstein"

In [48]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.57587589 0.07010333]
 [0.33486232 0.16553155]
 [0.86446577 0.88011575]
 [0.44352234 0.67169143]
 [0.25189963 0.9542801 ]]
[7.68574796e+03 3.49614116e+02 1.08326082e+04 1.50565183e+04
 5.47160170e+05]


### 5.4 - Goldstein price

In [49]:
function_name = "Goldstein price"

In [50]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.00206197 0.54511762]
 [0.72017102 0.11426736]
 [0.83198913 0.14335659]
 [0.71555694 0.31414643]
 [0.25431863 0.89282525]]
[ 1.21984743  0.06423523  0.82315179 -0.63788341  1.6852451 ]


### 5.5 - Iooss1

In [51]:
function_name = "Iooss1"

In [52]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.34328755 0.12872744]
 [0.86051216 0.65539784]
 [0.00872617 0.04223784]
 [0.78536766 0.46116125]
 [0.20367506 0.62738004]]
[0.27323933 1.50016017 1.8847338  1.96874601 1.31207403]


### 5.6 - Iooss2

In [53]:
function_name = "Iooss2"

In [54]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.23059939 0.31474229]
 [0.12189128 0.30313537]
 [0.22502544 0.91242456]
 [0.61915597 0.97644473]
 [0.81661131 0.40907074]]
[ 0.07855648 -0.15537136  0.11427084  0.9740341   1.28950982]


### 5.7 - Two input toy

In [55]:
function_name = "Two input toy"

In [56]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.52522007 0.41758849]
 [0.32131147 0.5463326 ]
 [0.70892377 0.14876157]
 [0.51958408 0.01782649]
 [0.09040759 0.79838026]]
[ 8.06376422  7.90236058 10.33833874 11.58770403  5.05537373]


### 5.8 - Highly non linear

In [57]:
function_name = "Highly non linear"

In [58]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.94533106 0.28295287]
 [0.50191773 0.82335173]
 [0.40854363 0.36830317]
 [0.02419042 0.08848718]
 [0.59619356 0.75139803]]
[7.60236513 8.87298237 8.27481615 0.48684737 8.70890965]


### 5.9 - Mystery

In [59]:
function_name = "Mystery"

In [60]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.46729536 0.14942672]
 [0.95023082 0.92998525]
 [0.64329386 0.15810989]
 [0.68036139 0.50414455]
 [0.94022904 0.05115805]]
[10.07743798 16.67422769 10.4647347  -0.962847   12.86770282]


### 5.10 - Six hump camelback

In [61]:
function_name = "Six hump camelback"

In [62]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.15925719 0.6359678 ]
 [0.18017247 0.1440425 ]
 [0.9340544  0.8776928 ]
 [0.59638996 0.04817399]
 [0.73240504 0.54049417]]
[ 1.67604203  2.29376347  2.43742503 -0.3981894   2.15278963]


# 6 - Literature datasets nD

### 6.1 - Morokoff & Caflisch 1

In [63]:
function_name = "Morokoff & caflisch 1"

In [64]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.68985016 0.4738009 ]
 [0.35756267 0.49971618]
 [0.01109108 0.68297992]
 [0.30676094 0.66477147]
 [0.28142718 0.36033298]]
[1.28634613 0.95108714 0.19582736 1.01605856 0.71650223]


### 6.2 - Morokoff & Caflisch 2

In [65]:
function_name = "Morokoff & caflisch 2"

In [66]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.57843112 0.51147951]
 [0.63892408 0.47065875]
 [0.70485844 0.14940155]
 [0.99028346 0.52697875]
 [0.63361077 0.51654675]]
[0.94045974 0.92513313 1.06523865 0.6610373  0.90087758]


### 6.3 - Rosenbrock4

In [67]:
function_name = "Rosenbrock4"

In [68]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.09945578 0.58475819 0.52773217 0.3109735 ]
 [0.33255508 0.8801599  0.069915   0.23553331]
 [0.29262357 0.48145858 0.23615387 0.80523411]
 [0.508551   0.82284575 0.20566934 0.83756714]
 [0.05681093 0.33915969 0.48820046 0.39323963]]
[-0.94483406  0.42784655 -1.00081292 -0.18485374 -0.93425341]


### 6.4 - Hartman4

In [69]:
function_name = "Hartman4"

In [70]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.52224982 0.41935293 0.95269794 0.42482804]
 [0.29790662 0.68219315 0.4274284  0.17789811]
 [0.5646475  0.36066576 0.37360116 0.62245289]
 [0.19566544 0.18671762 0.35367705 0.62132593]
 [0.4870012  0.72228742 0.07388973 0.21096134]]
[-1.19912956 -0.61003772  0.26025562 -0.06459216 -0.16695835]


### 6.5 - Hartman6

In [71]:
function_name = "Hartman6"

In [72]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.73471141 0.27103556 0.4749064  0.98167852 0.2629269  0.5829899 ]
 [0.29918876 0.79138847 0.28352251 0.44066994 0.9728138  0.28136841]
 [0.19508435 0.04761508 0.0035854  0.09302518 0.31673614 0.45552956]
 [0.2012261  0.02798189 0.1161087  0.37246828 0.28117559 0.02724347]
 [0.70733203 0.57426311 0.04768157 0.75290867 0.90416557 0.6435038 ]]
[-1.33925419 -1.76351255 -1.91205671 -1.37956526 -1.33064003]


### 6.6 - Sphere6

In [73]:
function_name = "Sphere6"

In [74]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.02813008 0.62508211 0.95799349 0.04139403 0.18143494 0.88318012]
 [0.70793965 0.5676215  0.76734545 0.53970102 0.34138098 0.74731052]
 [0.88902886 0.50115792 0.15889402 0.25124933 0.13792857 0.89529146]
 [0.00715108 0.072822   0.21998578 0.25812994 0.99645633 0.71591584]
 [0.20695755 0.37672052 0.3097777  0.59967459 0.70747896 0.01451608]]
[-1.87440737 -1.88416718 -1.87908214 -1.86757459 -1.91523346]


### 6.7 - Wing weight

In [75]:
function_name = "Wing weight"

In [76]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[ 1.97728259e+02  2.56255635e+02  8.22169441e+00  1.64425309e+00
   3.20490118e+01  9.20868125e-01  1.06630327e-01  5.31964814e+00
   2.36243971e+03  7.90188124e-02]
 [ 1.86013564e+02  2.51688433e+02  8.97225741e+00 -7.15615553e-01
   3.64352044e+01  8.27570382e-01  1.13033050e-01  3.55216114e+00
   2.26252066e+03  2.75861385e-02]
 [ 1.51020108e+02  2.37953486e+02  8.91911684e+00  2.85286218e+00
   2.34254284e+01  6.62505951e-01  8.47667198e-02  5.95984315e+00
   2.36194976e+03  3.34266956e-02]
 [ 1.83627460e+02  2.29378092e+02  7.91315258e+00 -6.26965195e+00
   1.69020166e+01  7.16822367e-01  8.24863960e-02  3.39629349e+00
   1.96352525e+03  5.24878273e-02]
 [ 1.91533234e+02  2.43296179e+02  9.52157889e+00  5.78041280e+00
   4.20339864e+01  7.31016290e-01  1.78308607e-01  5.63833713e+00
   1.82039955e+03  7.48598470e-02]]
[         nan 376.99298963          nan 272.74041911 351.58499162]


C:\Users/L2S/Desktop/Efficient_and_reliable_GP\Code\data_generation\samplers.py:364: RuntimeWarning: invalid value encountered in scalar power
  y                                       = 0.036 * x1**0.758 * x2**0.0035 * (x3 / np.cos(x4)**2)**0.6 * x5**0.006 * x6**0.04 * (100 * x7 / np.cos(x4))**(-0.3) * (x8 * x9)**0.49 + x1 * x10


### 6.8 - Sobol

In [77]:
function_name = "Sobol"

In [78]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.6536767  0.92211144]
 [0.23743086 0.7559478 ]
 [0.98813819 0.90806586]
 [0.2931408  0.29758779]
 [0.2837165  0.3157766 ]]
[0.85788241 1.02735548 1.56113051 0.89790682 0.91026116]


### 6.9 - Ishigami

In [79]:
function_name = "Ishigami"

In [80]:
function_X, function_Y = sampler          (N_function, function_name, sampler_parameters)
X         , Y          = extract_K_samples(function_X, function_Y, N_train + N_test)
train_X   , train_Y    = X[:N_train], Y[:N_train]
test_X    , test_Y     = X[N_train:], Y[N_train:]
print(train_X[:5])
print(train_Y[:5])

[[0.00314595 0.29277425 0.09731973]
 [0.07103172 0.32969402 0.87448232]
 [0.58839979 0.82587696 0.28859341]
 [0.12503118 0.23299191 0.39165817]
 [0.15696856 0.7431668  0.87514387]]
[6.40567771 3.63209932 6.21738777 6.19793063 3.57882379]
